from typing import *
from Instances import Instances,Instance
from Capabilities import Capabilities,CapabilityEnum

class Clusterer():
    def buildClusterer(self,data:Instances):...
    def clusterInstance(self,instance:Instance):...
    def distributionForInstance(self,instance:Instance):...
    def numberOfClusters(self):...
    def getCapabilities(self)->Capabilities:...