from core.Instances import Instances, Instance

from core.Capabilities import Capabilities


class Clusterer():
    def buildClusterer(self,data:Instances):...
    def clusterInstance(self,instance:Instance):...
    def distributionForInstance(self,instance:Instance):...
    def numberOfClusters(self):...
    def getCapabilities(self)-> Capabilities:...