# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1009, 756)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1009, 756))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setEnabled(True)
        self.tab.setObjectName("tab")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(10, 70, 981, 51))
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 50, 72, 15))
        self.label.setObjectName("label")
        self.summaryPanel = QtWidgets.QFrame(self.tab)
        self.summaryPanel.setGeometry(QtCore.QRect(10, 160, 491, 61))
        self.summaryPanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.summaryPanel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.summaryPanel.setObjectName("summaryPanel")
        self.layoutWidget = QtWidgets.QWidget(self.summaryPanel)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 471, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.name_lab = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.name_lab.setFont(font)
        self.name_lab.setObjectName("name_lab")
        self.horizontalLayout_6.addWidget(self.name_lab)
        self.gridLayout.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.attr_lab = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.attr_lab.setFont(font)
        self.attr_lab.setObjectName("attr_lab")
        self.horizontalLayout_4.addWidget(self.attr_lab)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 1, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.instance_lab = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.instance_lab.setFont(font)
        self.instance_lab.setObjectName("instance_lab")
        self.horizontalLayout_7.addWidget(self.instance_lab)
        self.gridLayout.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.weight_lab = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.weight_lab.setFont(font)
        self.weight_lab.setObjectName("weight_lab")
        self.horizontalLayout_5.addWidget(self.weight_lab)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(10, 130, 141, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(10, 230, 101, 21))
        self.label_3.setObjectName("label_3")
        self.attrPanel = QtWidgets.QFrame(self.tab)
        self.attrPanel.setGeometry(QtCore.QRect(10, 260, 491, 431))
        self.attrPanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.attrPanel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.attrPanel.setObjectName("attrPanel")
        self.attr_table = QtWidgets.QTableWidget(self.attrPanel)
        self.attr_table.setGeometry(QtCore.QRect(11, 48, 471, 331))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.attr_table.setFont(font)
        self.attr_table.setObjectName("attr_table")
        self.attr_table.setColumnCount(0)
        self.attr_table.setRowCount(0)
        self.remove_btn = QtWidgets.QPushButton(self.attrPanel)
        self.remove_btn.setGeometry(QtCore.QRect(20, 390, 451, 31))
        self.remove_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.remove_btn.setCheckable(False)
        self.remove_btn.setObjectName("remove_btn")
        self.layoutWidget1 = QtWidgets.QWidget(self.attrPanel)
        self.layoutWidget1.setGeometry(QtCore.QRect(19, 10, 451, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(70)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.all_btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.all_btn.setObjectName("all_btn")
        self.horizontalLayout_3.addWidget(self.all_btn)
        self.none_btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.none_btn.setObjectName("none_btn")
        self.horizontalLayout_3.addWidget(self.none_btn)
        self.invert_btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.invert_btn.setObjectName("invert_btn")
        self.horizontalLayout_3.addWidget(self.invert_btn)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(520, 130, 161, 20))
        self.label_4.setObjectName("label_4")
        self.attrSummaryPanel = QtWidgets.QFrame(self.tab)
        self.attrSummaryPanel.setGeometry(QtCore.QRect(520, 160, 471, 231))
        self.attrSummaryPanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.attrSummaryPanel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.attrSummaryPanel.setObjectName("attrSummaryPanel")
        self.selected_table = QtWidgets.QTableWidget(self.attrSummaryPanel)
        self.selected_table.setGeometry(QtCore.QRect(10, 50, 451, 171))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.selected_table.setFont(font)
        self.selected_table.setObjectName("selected_table")
        self.selected_table.setColumnCount(0)
        self.selected_table.setRowCount(0)
        self.layoutWidget2 = QtWidgets.QWidget(self.attrSummaryPanel)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 0, 451, 51))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_2.setContentsMargins(8, 0, 8, 0)
        self.gridLayout_2.setHorizontalSpacing(10)
        self.gridLayout_2.setVerticalSpacing(3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_11.addWidget(self.label_20)
        self.select_attr_unique = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_attr_unique.sizePolicy().hasHeightForWidth())
        self.select_attr_unique.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.select_attr_unique.setFont(font)
        self.select_attr_unique.setObjectName("select_attr_unique")
        self.horizontalLayout_11.addWidget(self.select_attr_unique)
        self.gridLayout_2.addLayout(self.horizontalLayout_11, 1, 2, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(5)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_12.addWidget(self.label_18)
        self.select_attr_distinct = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.select_attr_distinct.setFont(font)
        self.select_attr_distinct.setObjectName("select_attr_distinct")
        self.horizontalLayout_12.addWidget(self.select_attr_distinct)
        self.gridLayout_2.addLayout(self.horizontalLayout_12, 1, 1, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(5)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_13.addWidget(self.label_16)
        self.select_attr_missing = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.select_attr_missing.setFont(font)
        self.select_attr_missing.setObjectName("select_attr_missing")
        self.horizontalLayout_13.addWidget(self.select_attr_missing)
        self.gridLayout_2.addLayout(self.horizontalLayout_13, 1, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.select_attr_weight_lab = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_attr_weight_lab.sizePolicy().hasHeightForWidth())
        self.select_attr_weight_lab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.select_attr_weight_lab.setFont(font)
        self.select_attr_weight_lab.setObjectName("select_attr_weight_lab")
        self.horizontalLayout_9.addWidget(self.select_attr_weight_lab)
        self.select_attr_weight = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.select_attr_weight.setFont(font)
        self.select_attr_weight.setObjectName("select_attr_weight")
        self.horizontalLayout_9.addWidget(self.select_attr_weight)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 0, 1, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        self.select_attr_name = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.select_attr_name.setFont(font)
        self.select_attr_name.setObjectName("select_attr_name")
        self.horizontalLayout_8.addWidget(self.select_attr_name)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_10.addWidget(self.label_14)
        self.select_attr_type = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_attr_type.sizePolicy().hasHeightForWidth())
        self.select_attr_type.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.select_attr_type.setFont(font)
        self.select_attr_type.setObjectName("select_attr_type")
        self.horizontalLayout_10.addWidget(self.select_attr_type)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 0, 2, 1, 1)
        self.attr_combo = QtWidgets.QComboBox(self.tab)
        self.attr_combo.setGeometry(QtCore.QRect(520, 401, 471, 31))
        self.attr_combo.setObjectName("attr_combo")
        self.layoutWidget3 = QtWidgets.QWidget(self.tab)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 10, 321, 30))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.open_btn = QtWidgets.QPushButton(self.layoutWidget3)
        self.open_btn.setObjectName("open_btn")
        self.horizontalLayout.addWidget(self.open_btn)
        self.edit_btn = QtWidgets.QPushButton(self.layoutWidget3)
        self.edit_btn.setObjectName("edit_btn")
        self.horizontalLayout.addWidget(self.edit_btn)
        self.save_btn = QtWidgets.QPushButton(self.layoutWidget3)
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout.addWidget(self.save_btn)
        self.draw_area = MatplotlibWidget(self.tab)
        self.draw_area.setGeometry(QtCore.QRect(510, 440, 491, 261))
        self.draw_area.setObjectName("draw_area")
        self.apply_btn = QtWidgets.QPushButton(self.tab)
        self.apply_btn.setGeometry(QtCore.QRect(876, 80, 93, 28))
        self.apply_btn.setObjectName("apply_btn")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(143, 80, 711, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.chose_btn = TreeNodeButton(self.tab)
        self.chose_btn.setGeometry(QtCore.QRect(30, 80, 93, 28))
        self.chose_btn.setObjectName("chose_btn")
        self.label.raise_()
        self.summaryPanel.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.attrPanel.raise_()
        self.label_4.raise_()
        self.attrSummaryPanel.raise_()
        self.attr_combo.raise_()
        self.layoutWidget.raise_()
        self.draw_area.raise_()
        self.frame.raise_()
        self.apply_btn.raise_()
        self.label_9.raise_()
        self.chose_btn.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Filter"))
        self.label_5.setText(_translate("MainWindow", "Relation:"))
        self.name_lab.setText(_translate("MainWindow", "None"))
        self.label_7.setText(_translate("MainWindow", "Attributes:"))
        self.attr_lab.setText(_translate("MainWindow", "None"))
        self.label_6.setText(_translate("MainWindow", "Instance:"))
        self.instance_lab.setText(_translate("MainWindow", "None"))
        self.label_8.setText(_translate("MainWindow", "Sum of weight:"))
        self.weight_lab.setText(_translate("MainWindow", "None"))
        self.label_2.setText(_translate("MainWindow", "Current relation"))
        self.label_3.setText(_translate("MainWindow", "Attributes"))
        self.remove_btn.setText(_translate("MainWindow", "Remove"))
        self.all_btn.setText(_translate("MainWindow", "All"))
        self.none_btn.setText(_translate("MainWindow", "None"))
        self.invert_btn.setText(_translate("MainWindow", "Invert"))
        self.label_4.setText(_translate("MainWindow", "Selected attribute"))
        self.label_20.setText(_translate("MainWindow", "Unique:"))
        self.select_attr_unique.setText(_translate("MainWindow", "None"))
        self.label_18.setText(_translate("MainWindow", "Distinct:"))
        self.select_attr_distinct.setText(_translate("MainWindow", "None"))
        self.label_16.setText(_translate("MainWindow", "Missing:"))
        self.select_attr_missing.setText(_translate("MainWindow", "None"))
        self.select_attr_weight_lab.setText(_translate("MainWindow", "Weight:"))
        self.select_attr_weight.setText(_translate("MainWindow", "None"))
        self.label_10.setText(_translate("MainWindow", "Name:"))
        self.select_attr_name.setText(_translate("MainWindow", "None"))
        self.label_14.setText(_translate("MainWindow", "Type:"))
        self.select_attr_type.setText(_translate("MainWindow", "None"))
        self.open_btn.setText(_translate("MainWindow", "打开"))
        self.edit_btn.setText(_translate("MainWindow", "编辑"))
        self.save_btn.setText(_translate("MainWindow", "保存"))
        self.apply_btn.setText(_translate("MainWindow", "确定"))
        self.label_9.setText(_translate("MainWindow", "None"))
        self.chose_btn.setText(_translate("MainWindow", "Choose"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "预处理"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "分类"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "聚类"))

from MatplotlibWidget import MatplotlibWidget
from TreeNodeButton import TreeNodeButton
import apprcc_rc
