# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Viewer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 600)
        self.viewTable = TableWidget(Form)
        self.viewTable.setGeometry(QtCore.QRect(10, 30, 981, 511))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.viewTable.setFont(font)
        self.viewTable.setObjectName("viewTable")
        self.viewTable.setColumnCount(0)
        self.viewTable.setRowCount(0)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 153, 17))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.relationName = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.relationName.sizePolicy().hasHeightForWidth())
        self.relationName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.relationName.setFont(font)
        self.relationName.setObjectName("relationName")
        self.horizontalLayout.addWidget(self.relationName)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(580, 560, 401, 30))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.addInstance = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.addInstance.setFont(font)
        self.addInstance.setObjectName("addInstance")
        self.horizontalLayout_2.addWidget(self.addInstance)
        self.Undo = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Undo.setFont(font)
        self.Undo.setObjectName("Undo")
        self.horizontalLayout_2.addWidget(self.Undo)
        self.Ok = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Ok.setFont(font)
        self.Ok.setObjectName("Ok")
        self.horizontalLayout_2.addWidget(self.Ok)
        self.Cancel = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Cancel.setFont(font)
        self.Cancel.setObjectName("Cancel")
        self.horizontalLayout_2.addWidget(self.Cancel)

        self.retranslateUi(Form)
        self.Cancel.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Relation:"))
        self.relationName.setText(_translate("Form", "None"))
        self.addInstance.setText(_translate("Form", "Add instance"))
        self.Undo.setText(_translate("Form", "Undo"))
        self.Ok.setText(_translate("Form", "Ok"))
        self.Cancel.setText(_translate("Form", "Cancel"))

from TableWidget import TableWidget
