from enum import Enum

class Plot2D(Enum):
    MAX_SHAPES=5
    ERROR_SHAPE=1000
    MISSING_SHAPE=2000
    CONST_AUTOMATIC_SHAPE=-1
    X_SHAPE=0
    PLUS_SHAPE = 1
    DIAMOND_SHAPE = 2
    TRIANGLEUP_SHAPE = 3
    TRIANGLEDOWN_SHAPE = 4
    DEFAULT_SHAPE_SIZE = 10
